
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MANNAR
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jBalok = new javax.swing.JPanel();
        etPanjang = new javax.swing.JTextField();
        etLebar = new javax.swing.JTextField();
        etTinggi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bHitung = new javax.swing.JButton();
        jKubus = new javax.swing.JPanel();
        etSisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bVolumeKubus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jBola = new javax.swing.JPanel();
        etJari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bVolumeBola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBalok.setLayout(null);
        jBalok.add(etPanjang);
        etPanjang.setBounds(167, 38, 110, 30);
        jBalok.add(etLebar);
        etLebar.setBounds(167, 76, 110, 30);
        jBalok.add(etTinggi);
        etTinggi.setBounds(167, 120, 110, 30);

        jLabel1.setText("Panjang");
        jBalok.add(jLabel1);
        jLabel1.setBounds(63, 41, 60, 30);

        jLabel2.setText("Lebar");
        jBalok.add(jLabel2);
        jLabel2.setBounds(63, 79, 50, 30);

        jLabel3.setText("Tinggi");
        jBalok.add(jLabel3);
        jLabel3.setBounds(63, 123, 50, 30);

        jLabel4.setText("cm");
        jBalok.add(jLabel4);
        jLabel4.setBounds(290, 120, 20, 20);

        jLabel5.setText("cm");
        jBalok.add(jLabel5);
        jLabel5.setBounds(290, 80, 20, 20);

        jLabel6.setText("cm");
        jBalok.add(jLabel6);
        jLabel6.setBounds(290, 40, 20, 20);

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        jBalok.add(bHitung);
        bHitung.setBounds(170, 160, 110, 30);

        jTabbedPane1.addTab("Balok", jBalok);

        jKubus.setLayout(null);
        jKubus.add(etSisi);
        etSisi.setBounds(55, 63, 90, 30);

        jLabel7.setText("cm");
        jKubus.add(jLabel7);
        jLabel7.setBounds(150, 60, 20, 20);

        bVolumeKubus.setText("Volume");
        bVolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolumeKubusActionPerformed(evt);
            }
        });
        jKubus.add(bVolumeKubus);
        bVolumeKubus.setBounds(55, 94, 70, 30);

        jLabel10.setText("Panjang Sisi");
        jKubus.add(jLabel10);
        jLabel10.setBounds(55, 31, 70, 30);

        jTabbedPane1.addTab("Kubus", jKubus);

        jBola.setLayout(null);
        jBola.add(etJari);
        etJari.setBounds(34, 55, 110, 30);

        jLabel8.setText("cm");
        jBola.add(jLabel8);
        jLabel8.setBounds(150, 50, 20, 20);

        bVolumeBola.setText("Volume");
        bVolumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolumeBolaActionPerformed(evt);
            }
        });
        jBola.add(bVolumeBola);
        bVolumeBola.setBounds(34, 86, 70, 30);

        jLabel11.setText("Panjang Sisi");
        jBola.add(jLabel11);
        jLabel11.setBounds(40, 30, 70, 30);

        jTabbedPane1.addTab("Bola", jBola);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 400, 230);

        jLabel9.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 10, 220, 50);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(etPanjang.getText());
        lebar = Integer.parseInt(etLebar.getText());
        tinggi = Integer.parseInt(etTinggi.getText());
        int hasil = panjang*lebar*tinggi;
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah : "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void bVolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolumeKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(etSisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Kubus Adalah : "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bVolumeKubusActionPerformed

    private void bVolumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolumeBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(etJari.getText());
        float hasil1 = (float) (4*22/7*jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Bola Adalah : "+hasil1,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e,"luas",
                    JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_bVolumeBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bVolumeBola;
    private javax.swing.JButton bVolumeKubus;
    private javax.swing.JTextField etJari;
    private javax.swing.JTextField etLebar;
    private javax.swing.JTextField etPanjang;
    private javax.swing.JTextField etSisi;
    private javax.swing.JTextField etTinggi;
    private javax.swing.JPanel jBalok;
    private javax.swing.JPanel jBola;
    private javax.swing.JPanel jKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
